### ISSUE TITLE
Introducción a machine mearning y algoritmos genéticos

### ISSUE THREAD

**Issue by baromigue** [algorithms-study-group-ba/charlas#2]
### Título
Introducción a Algoritmos Genéticos y Machine Learning.

### Descripción
Algoritmos genéticos y machine learning. ¿Qué son? ¿Cómo se usan? ¿Para qué? Un panorama general e introductorio sobre estos conceptos y sus posibles aplicaciones en la práctica. Ventajas y desventajas, consideraciones a la hora de pensar en usarlos. Veremos algunos ejemplos de cómo usar la "evolución" y la selección "no tan natural" para resolver algunos problemas.

### Sobre el orador
**Twitter:** @baromigue

### Extra
Tenes la charla preparada?
No

En qué mes la podrías dar?
Junio (fines de)

**Comment by nisnardi** [comment]
Esta charla queda para Julio

**Comment by nisnardi** [comment]
Gracias Migue, muy buena charla!
