### ISSUE TITLE
Practicando Algoritmos Online

### ISSUE THREAD

**Issue by rschifini** [algorithms-study-group-ba/charlas#5]
### Título
Practicando Algoritmos Online

### Descripción
Alguna vez quisieron practicar o aprender algún algoritmo y no se les ocurre que hacer? No se preocupen mas, LMGTFY (let me google that for you)! Les voy a mostrar un pequeño grupo de sitios donde pueden encontrar cientos de problemas sobre los que pueden practicar. Y no se preocupen si no saben A*, el motor de Google o Facebook, yo tampoco los se.  Resolveremos unos dos o tres problemas elegidos en el momento. No se olviden de traer su cerebro!

### Sobre el orador
Tengo titulo de Doctor en Física pero me gusta resolver problemas con software. Programo por diversión desde mis 12 años (+-1) y un poco mas profesionalmente desde hace 15 años.  Puedo desarrollar en Matlab, R y JavaScript (ECMAScript 6). También me defiendo con otros como Python y SQL.

**Sitio:** js-adventures.netne.net

### Recursos
**Slides de la presentación:**
https://es.slideshare.net/ricardoschifini/practicando-algoritmos-online

### Extra
Tenes la charla preparada?
Si, tengo un MVP. Estaré agregando algún que otro detalle pero lo mínimo esta listo.

En qué mes la podrías dar?
Mañana

Avisanos si necesitas algo especial para poder dar la charla así lo podemos planificar con tiempo.
PIZARRÓN PLS !!!! Creo que puede llegar a ser necesario.

**Comment by nisnardi** [comment]
Gracias Ricardo, muy buena charla, ahora a hacer ejercicios!
